services:
  ha-manager-enterprise:
    container_name: ha-manager-enterprise
    image: ha-manager-enterprise
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - "16000:8000"
    depends_on:
      app_db:
        condition: service_healthy

  app_db:
    container_name: app_db
    hostname: app_db
    image: library/postgres:14.1
    env_file:
      - .env
    volumes:
      - app_pg_data:/var/lib/postgresql/data
      - app_pg_data_backups:/backups
      - ./scripts/postgres:/scripts
    ports:
      - "65432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  app_pg_data:
    driver: "local"
  app_pg_data_backups:
    driver: "local"
